### ISSUE TITLE
Add maximum test duration threshold

### ISSUE THREAD

**Issue by achudzik** [marcingrzejszczak/gradle-test-profiler#11]
There should be also configurable threshold for maximum duration of single test, enabled in CI builds.

**Comment by marcingrzejszczak** [comment]
It's impossible to add in Gradle in TestExcution listener unfortunately.

I have some ideas though ;) 

## Spock extension

Since we are using Spock (next we could add JUnit) we could go with creating a Spock extension that would listen on method execution:

```
org.spockframework.runtime.extension.IMethodInvocation
```

and then would wrap the `proced()` method with verification of time execution. If this time would be too big then we would fail the test (don't know yet how).

We could base it on org.spockframework.runtime.extension.builtin.TimeoutExtension

## Junit rule

`org.junit.rules.Timeout` rule for timeouting globally all methods in a class. It sucks though cause it's a class rule.

## Create cusotm JUnit runner!

What about the ones that already use Spring stuff? We can't do it :/

## Dirty hacks to solve JUnit rule issue

We can iterate over all tests and add the Timeout rule ;) That sounds terrible but it's almost 2 a.m. and I'm running out of good ideas ;) The only benefit I see here that it would work for both Spock and JUnit.

## Terribly terrible hack

If someone knows how to customize this - org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor#processTestClass and this - org/gradle/api/internal/tasks/testing/junit/JUnitTestClassExecuter.java:86 then be my guest :P

@szpak @achudzik @kamilszymanski help!

**Comment by marcingrzejszczak** [comment]
For JUnit Java I add with Javassist Timeout @Rule
For Groovy I add with Javassist Timeout @Rule
For Spock I add a global extension that timeouts the build
